server:
  port: 8095

spring:
  datasource:
    username: root
    password: "000000"
    url: jdbc:mysql://10.110.181.205:3306/shiro?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.demoshiro.entity
#showSql
logging:
  level:
    com:
      example:
        demomysql:
          mapper : debug