server:
  port: 8088

spring:
  datasource:
    username: root
    password: "000000"
    url: jdbc:mysql://192.168.1.114:3306/school?useUnicode=true&characterEncoding=utf8
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.demomysql.entity
#showSql
logging:
  level:
    com:
      example:
        demomysql:
          mapper : debug
